version: '3'
services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "softdare"
      POSTGRES_PASSWORD: "softdare"
    volumes:
      - postgres:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "6001:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=softdare
      - RABBITMQ_DEFAULT_PASS=softdare
volumes:
  postgres:
