db:
  username: "softdare"
  password: "softdare"
  dbName: "postgres"
  host: "localhost"
  port: "5432"

server:
  address: ":4000"

session:
  key: "u46IpCV9y5Vlur8YvODJEhgOY8m9JVE4"

rabbitmq:
  username: "softdare"
  password: "softdare"
  host: "localhost"
  port: "6001"
  queues:
    - "comment-created"
    - "post-created"
    - "user-follow-created"